<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="8.0.8" />
    <PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../HabitosNet/Resources/Raw/SeedData.json" Link="SeedData.json" CopyToOutputDirectory="PreserveNewest" />
    <Compile Include="../HabitosNet/Data/*.cs" Link="App/Data/%(Filename)%(Extension)" />
    <Compile Include="../HabitosNet/Models/Project.cs" Link="App/Models/Project.cs" />
    <Compile Include="../HabitosNet/Models/ProjectTask.cs" Link="App/Models/ProjectTask.cs" />
    <Compile Include="../HabitosNet/Models/Category.cs" Link="App/Models/Category.cs" />
    <Compile Include="../HabitosNet/Models/Tag.cs" Link="App/Models/Tag.cs" />
    <Compile Include="../HabitosNet/Models/IconData.cs" Link="App/Models/IconData.cs" />
    <Compile Include="../HabitosNet/PageModels/ProjectDetailPageModel.cs" Link="App/PageModels/ProjectDetailPageModel.cs" />
    <Compile Include="../HabitosNet/PageModels/TaskDetailPageModel.cs" Link="App/PageModels/TaskDetailPageModel.cs" />
    <Compile Include="../HabitosNet/PageModels/ManageMetaPageModel.cs" Link="App/PageModels/ManageMetaPageModel.cs" />
    <Compile Include="../HabitosNet/PageModels/IProjectTaskPageModel.cs" Link="App/PageModels/IProjectTaskPageModel.cs" />
    <Compile Include="../HabitosNet/Services/IErrorHandler.cs" Link="App/Services/IErrorHandler.cs" />
    <Compile Include="../HabitosNet/Services/ModalErrorHandler.cs" Link="App/Services/ModalErrorHandler.cs" />
    <Compile Include="../HabitosNet/Utilities/TaskUtilities.cs" Link="App/Utilities/TaskUtilities.cs" />
    <Compile Include="../HabitosNet/Resources/Fonts/FluentUI.cs" Link="App/Fonts/FluentUI.cs" />
  </ItemGroup>
</Project>
